export const COUNTRIES = [
  { code: 'AF', pt: 'Afeganistão', en: 'Afghanistan', capital: 'Kabul' },
  { code: 'ZA', pt: 'África do Sul', en: 'South Africa', capital: 'Pretoria' },
  { code: 'AL', pt: 'Albânia', en: 'Albania', capital: 'Tirana' },
  { code: 'DE', pt: 'Alemanha', en: 'Germany', capital: 'Berlin' },
  { code: 'AD', pt: 'Andorra', en: 'Andorra', capital: 'Andorra la Vella' },
  { code: 'AO', pt: 'Angola', en: 'Angola', capital: 'Luanda' },
  { code: 'AG', pt: 'Antígua e Barbuda', en: 'Antigua and Barbuda', capital: "Saint John's" },
  { code: 'SA', pt: 'Arábia Saudita', en: 'Saudi Arabia', capital: 'Riyadh' },
  { code: 'DZ', pt: 'Argélia', en: 'Algeria', capital: 'Algiers' },
  { code: 'AR', pt: 'Argentina', en: 'Argentina', capital: 'Buenos Aires' },
  { code: 'AM', pt: 'Armênia', en: 'Armenia', capital: 'Yerevan' },
  { code: 'AU', pt: 'Austrália', en: 'Australia', capital: 'Canberra' },
  { code: 'AT', pt: 'Áustria', en: 'Austria', capital: 'Vienna' },
  { code: 'AZ', pt: 'Azerbaijão', en: 'Azerbaijan', capital: 'Baku' },
  { code: 'BS', pt: 'Bahamas', en: 'Bahamas', capital: 'Nassau' },
  { code: 'BH', pt: 'Bahrein', en: 'Bahrain', capital: 'Manama' },
  { code: 'BD', pt: 'Bangladesh', en: 'Bangladesh', capital: 'Dhaka' },
  { code: 'BB', pt: 'Barbados', en: 'Barbados', capital: 'Bridgetown' },
  { code: 'BY', pt: 'Belarus', en: 'Belarus', capital: 'Minsk' },
  { code: 'BE', pt: 'Bélgica', en: 'Belgium', capital: 'Brussels' },
  { code: 'BZ', pt: 'Belize', en: 'Belize', capital: 'Belmopan' },
  { code: 'BJ', pt: 'Benin', en: 'Benin', capital: 'Porto-Novo' },
  { code: 'BO', pt: 'Bolívia', en: 'Bolivia', capital: 'Sucre' },
  { code: 'BA', pt: 'Bósnia e Herzegovina', en: 'Bosnia and Herzegovina', capital: 'Sarajevo' },
  { code: 'BW', pt: 'Botsuana', en: 'Botswana', capital: 'Gaborone' },
  { code: 'BR', pt: 'Brasil', en: 'Brazil', capital: 'Brasília' },
  { code: 'BN', pt: 'Brunei', en: 'Brunei', capital: 'Bandar Seri Begawan' },
  { code: 'BG', pt: 'Bulgária', en: 'Bulgaria', capital: 'Sofia' },
  { code: 'BF', pt: 'Burkina Faso', en: 'Burkina Faso', capital: 'Ouagadougou' },
  { code: 'BI', pt: 'Burundi', en: 'Burundi', capital: 'Gitega' },
  { code: 'BT', pt: 'Butão', en: 'Bhutan', capital: 'Thimphu' },
  { code: 'CV', pt: 'Cabo Verde', en: 'Cape Verde', capital: 'Praia' },
  { code: 'CM', pt: 'Camarões', en: 'Cameroon', capital: 'Yaoundé' },
  { code: 'KH', pt: 'Camboja', en: 'Cambodia', capital: 'Phnom Penh' },
  { code: 'CA', pt: 'Canadá', en: 'Canada', capital: 'Ottawa' },
  { code: 'QA', pt: 'Catar', en: 'Qatar', capital: 'Doha' },
  { code: 'KZ', pt: 'Cazaquistão', en: 'Kazakhstan', capital: 'Astana' },
  { code: 'TD', pt: 'Chade', en: 'Chad', capital: "N'Djamena" },
  { code: 'CL', pt: 'Chile', en: 'Chile', capital: 'Santiago' },
  { code: 'CN', pt: 'China', en: 'China', capital: 'Beijing' },
  { code: 'CY', pt: 'Chipre', en: 'Cyprus', capital: 'Nicosia' },
  { code: 'CO', pt: 'Colômbia', en: 'Colombia', capital: 'Bogotá' },
  { code: 'KM', pt: 'Comores', en: 'Comoros', capital: 'Moroni' },
  { code: 'CG', pt: 'Congo', en: 'Congo', capital: 'Brazzaville' },
  { code: 'CD', pt: 'Congo (RD)', en: 'DR Congo', capital: 'Kinshasa' },
  { code: 'KR', pt: 'Coreia do Sul', en: 'South Korea', capital: 'Seoul' },
  { code: 'KP', pt: 'Coreia do Norte', en: 'North Korea', capital: 'Pyongyang' },
  { code: 'CI', pt: 'Costa do Marfim', en: 'Ivory Coast', capital: 'Yamoussoukro' },
  { code: 'CR', pt: 'Costa Rica', en: 'Costa Rica', capital: 'San José' },
  { code: 'HR', pt: 'Croácia', en: 'Croatia', capital: 'Zagreb' },
  { code: 'CU', pt: 'Cuba', en: 'Cuba', capital: 'Havana' },
  { code: 'DK', pt: 'Dinamarca', en: 'Denmark', capital: 'Copenhagen' },
  { code: 'DJ', pt: 'Djibuti', en: 'Djibouti', capital: 'Djibouti' },
  { code: 'DM', pt: 'Dominica', en: 'Dominica', capital: 'Roseau' },
  { code: 'DO', pt: 'República Dominicana', en: 'Dominican Republic', capital: 'Santo Domingo' },
  { code: 'EG', pt: 'Egito', en: 'Egypt', capital: 'Cairo' },
  { code: 'SV', pt: 'El Salvador', en: 'El Salvador', capital: 'San Salvador' },
  { code: 'AE', pt: 'Emirados Árabes Unidos', en: 'United Arab Emirates', capital: 'Abu Dhabi' },
  { code: 'EC', pt: 'Equador', en: 'Ecuador', capital: 'Quito' },
  { code: 'ER', pt: 'Eritreia', en: 'Eritrea', capital: 'Asmara' },
  { code: 'SK', pt: 'Eslováquia', en: 'Slovakia', capital: 'Bratislava' },
  { code: 'SI', pt: 'Eslovênia', en: 'Slovenia', capital: 'Ljubljana' },
  { code: 'ES', pt: 'Espanha', en: 'Spain', capital: 'Madrid' },
  { code: 'US', pt: 'Estados Unidos', en: 'United States', capital: 'Washington' },
  { code: 'EE', pt: 'Estônia', en: 'Estonia', capital: 'Tallinn' },
  { code: 'ET', pt: 'Etiópia', en: 'Ethiopia', capital: 'Addis Ababa' },
  { code: 'FJ', pt: 'Fiji', en: 'Fiji', capital: 'Suva' },
  { code: 'PH', pt: 'Filipinas', en: 'Philippines', capital: 'Manila' },
  { code: 'FI', pt: 'Finlândia', en: 'Finland', capital: 'Helsinki' },
  { code: 'FR', pt: 'França', en: 'France', capital: 'Paris' },
  { code: 'GA', pt: 'Gabão', en: 'Gabon', capital: 'Libreville' },
  { code: 'GM', pt: 'Gâmbia', en: 'Gambia', capital: 'Banjul' },
  { code: 'GH', pt: 'Gana', en: 'Ghana', capital: 'Accra' },
  { code: 'GE', pt: 'Geórgia', en: 'Georgia', capital: 'Tbilisi' },
  { code: 'GD', pt: 'Granada', en: 'Grenada', capital: "Saint George's" },
  { code: 'GR', pt: 'Grécia', en: 'Greece', capital: 'Athens' },
  { code: 'GT', pt: 'Guatemala', en: 'Guatemala', capital: 'Guatemala City' },
  { code: 'GY', pt: 'Guiana', en: 'Guyana', capital: 'Georgetown' },
  { code: 'GN', pt: 'Guiné', en: 'Guinea', capital: 'Conakry' },
  { code: 'GW', pt: 'Guiné-Bissau', en: 'Guinea-Bissau', capital: 'Bissau' },
  { code: 'GQ', pt: 'Guiné Equatorial', en: 'Equatorial Guinea', capital: 'Malabo' },
  { code: 'HT', pt: 'Haiti', en: 'Haiti', capital: 'Port-au-Prince' },
  { code: 'HN', pt: 'Honduras', en: 'Honduras', capital: 'Tegucigalpa' },
  { code: 'HU', pt: 'Hungria', en: 'Hungary', capital: 'Budapest' },
  { code: 'YE', pt: 'Iêmen', en: 'Yemen', capital: 'Sanaa' },
  { code: 'IN', pt: 'Índia', en: 'India', capital: 'New Delhi' },
  { code: 'ID', pt: 'Indonésia', en: 'Indonesia', capital: 'Jakarta' },
  { code: 'IQ', pt: 'Iraque', en: 'Iraq', capital: 'Baghdad' },
  { code: 'IR', pt: 'Irã', en: 'Iran', capital: 'Tehran' },
  { code: 'IE', pt: 'Irlanda', en: 'Ireland', capital: 'Dublin' },
  { code: 'IS', pt: 'Islândia', en: 'Iceland', capital: 'Reykjavik' },
  { code: 'IL', pt: 'Israel', en: 'Israel', capital: 'Jerusalem' },
  { code: 'IT', pt: 'Itália', en: 'Italy', capital: 'Rome' },
  { code: 'JM', pt: 'Jamaica', en: 'Jamaica', capital: 'Kingston' },
  { code: 'JP', pt: 'Japão', en: 'Japan', capital: 'Tokyo' },
  { code: 'JO', pt: 'Jordânia', en: 'Jordan', capital: 'Amman' },
  { code: 'KW', pt: 'Kuwait', en: 'Kuwait', capital: 'Kuwait City' },
  { code: 'LA', pt: 'Laos', en: 'Laos', capital: 'Vientiane' },
  { code: 'LS', pt: 'Lesoto', en: 'Lesotho', capital: 'Maseru' },
  { code: 'LV', pt: 'Letônia', en: 'Latvia', capital: 'Riga' },
  { code: 'LB', pt: 'Líbano', en: 'Lebanon', capital: 'Beirut' },
  { code: 'LR', pt: 'Libéria', en: 'Liberia', capital: 'Monrovia' },
  { code: 'LY', pt: 'Líbia', en: 'Libya', capital: 'Tripoli' },
  { code: 'LT', pt: 'Lituânia', en: 'Lithuania', capital: 'Vilnius' },
  { code: 'LU', pt: 'Luxemburgo', en: 'Luxembourg', capital: 'Luxembourg' },
  { code: 'MG', pt: 'Madagascar', en: 'Madagascar', capital: 'Antananarivo' },
  { code: 'MY', pt: 'Malásia', en: 'Malaysia', capital: 'Kuala Lumpur' },
  { code: 'MW', pt: 'Malaui', en: 'Malawi', capital: 'Lilongwe' },
  { code: 'MV', pt: 'Maldivas', en: 'Maldives', capital: 'Malé' },
  { code: 'ML', pt: 'Mali', en: 'Mali', capital: 'Bamako' },
  { code: 'MT', pt: 'Malta', en: 'Malta', capital: 'Valletta' },
  { code: 'MA', pt: 'Marrocos', en: 'Morocco', capital: 'Rabat' },
  { code: 'MH', pt: 'Ilhas Marshall', en: 'Marshall Islands', capital: 'Majuro' },
  { code: 'MR', pt: 'Mauritânia', en: 'Mauritania', capital: 'Nouakchott' },
  { code: 'MU', pt: 'Maurício', en: 'Mauritius', capital: 'Port Louis' },
  { code: 'MX', pt: 'México', en: 'Mexico', capital: 'Mexico City' },
  { code: 'MM', pt: 'Mianmar', en: 'Myanmar', capital: 'Naypyidaw' },
  { code: 'MZ', pt: 'Moçambique', en: 'Mozambique', capital: 'Maputo' },
  { code: 'MD', pt: 'Moldávia', en: 'Moldova', capital: 'Chișinău' },
  { code: 'MC', pt: 'Mônaco', en: 'Monaco', capital: 'Monaco' },
  { code: 'MN', pt: 'Mongólia', en: 'Mongolia', capital: 'Ulaanbaatar' },
  { code: 'ME', pt: 'Montenegro', en: 'Montenegro', capital: 'Podgorica' },
  { code: 'NA', pt: 'Namíbia', en: 'Namibia', capital: 'Windhoek' },
  { code: 'NR', pt: 'Nauru', en: 'Nauru', capital: 'Yaren' },
  { code: 'NP', pt: 'Nepal', en: 'Nepal', capital: 'Kathmandu' },
  { code: 'NI', pt: 'Nicarágua', en: 'Nicaragua', capital: 'Managua' },
  { code: 'NE', pt: 'Níger', en: 'Niger', capital: 'Niamey' },
  { code: 'NG', pt: 'Nigéria', en: 'Nigeria', capital: 'Abuja' },
  { code: 'NO', pt: 'Noruega', en: 'Norway', capital: 'Oslo' },
  { code: 'NZ', pt: 'Nova Zelândia', en: 'New Zealand', capital: 'Wellington' },
  { code: 'OM', pt: 'Omã', en: 'Oman', capital: 'Muscat' },
  { code: 'NL', pt: 'Países Baixos', en: 'Netherlands', capital: 'Amsterdam' },
  { code: 'PW', pt: 'Palau', en: 'Palau', capital: 'Ngerulmud' },
  { code: 'PA', pt: 'Panamá', en: 'Panama', capital: 'Panama City' },
  { code: 'PG', pt: 'Papua-Nova Guiné', en: 'Papua New Guinea', capital: 'Port Moresby' },
  { code: 'PK', pt: 'Paquistão', en: 'Pakistan', capital: 'Islamabad' },
  { code: 'PY', pt: 'Paraguai', en: 'Paraguay', capital: 'Asunción' },
  { code: 'PE', pt: 'Peru', en: 'Peru', capital: 'Lima' },
  { code: 'PL', pt: 'Polônia', en: 'Poland', capital: 'Warsaw' },
  { code: 'PT', pt: 'Portugal', en: 'Portugal', capital: 'Lisbon' },
  { code: 'KE', pt: 'Quênia', en: 'Kenya', capital: 'Nairobi' },
  { code: 'KG', pt: 'Quirguistão', en: 'Kyrgyzstan', capital: 'Bishkek' },
  { code: 'GB', pt: 'Reino Unido', en: 'United Kingdom', capital: 'London' },
  { code: 'CF', pt: 'República Centro-Africana', en: 'Central African Republic', capital: 'Bangui' },
  { code: 'CZ', pt: 'República Tcheca', en: 'Czech Republic', capital: 'Prague' },
  { code: 'MK', pt: 'Macedônia do Norte', en: 'North Macedonia', capital: 'Skopje' },
  { code: 'RO', pt: 'Romênia', en: 'Romania', capital: 'Bucharest' },
  { code: 'RW', pt: 'Ruanda', en: 'Rwanda', capital: 'Kigali' },
  { code: 'RU', pt: 'Rússia', en: 'Russia', capital: 'Moscow' },
  { code: 'WS', pt: 'Samoa', en: 'Samoa', capital: 'Apia' },
  { code: 'SM', pt: 'San Marino', en: 'San Marino', capital: 'San Marino' },
  { code: 'LC', pt: 'Santa Lúcia', en: 'Saint Lucia', capital: 'Castries' },
  { code: 'KN', pt: 'São Cristóvão e Névis', en: 'Saint Kitts and Nevis', capital: 'Basseterre' },
  { code: 'ST', pt: 'São Tomé e Príncipe', en: 'São Tomé and Príncipe', capital: 'São Tomé' },
  { code: 'VC', pt: 'São Vicente e Granadinas', en: 'Saint Vincent', capital: 'Kingstown' },
  { code: 'SC', pt: 'Seicheles', en: 'Seychelles', capital: 'Victoria' },
  { code: 'SN', pt: 'Senegal', en: 'Senegal', capital: 'Dakar' },
  { code: 'SL', pt: 'Serra Leoa', en: 'Sierra Leone', capital: 'Freetown' },
  { code: 'RS', pt: 'Sérvia', en: 'Serbia', capital: 'Belgrade' },
  { code: 'SG', pt: 'Singapura', en: 'Singapore', capital: 'Singapore' },
  { code: 'SY', pt: 'Síria', en: 'Syria', capital: 'Damascus' },
  { code: 'SO', pt: 'Somália', en: 'Somalia', capital: 'Mogadishu' },
  { code: 'LK', pt: 'Sri Lanka', en: 'Sri Lanka', capital: 'Colombo' },
  { code: 'SZ', pt: 'Essuatíni', en: 'Eswatini', capital: 'Mbabane' },
  { code: 'SD', pt: 'Sudão', en: 'Sudan', capital: 'Khartoum' },
  { code: 'SS', pt: 'Sudão do Sul', en: 'South Sudan', capital: 'Juba' },
  { code: 'SE', pt: 'Suécia', en: 'Sweden', capital: 'Stockholm' },
  { code: 'CH', pt: 'Suíça', en: 'Switzerland', capital: 'Bern' },
  { code: 'SR', pt: 'Suriname', en: 'Suriname', capital: 'Paramaribo' },
  { code: 'TH', pt: 'Tailândia', en: 'Thailand', capital: 'Bangkok' },
  { code: 'TW', pt: 'Taiwan', en: 'Taiwan', capital: 'Taipei' },
  { code: 'TJ', pt: 'Tadjiquistão', en: 'Tajikistan', capital: 'Dushanbe' },
  { code: 'TZ', pt: 'Tanzânia', en: 'Tanzania', capital: 'Dodoma' },
  { code: 'TL', pt: 'Timor-Leste', en: 'Timor-Leste', capital: 'Dili' },
  { code: 'TG', pt: 'Togo', en: 'Togo', capital: 'Lomé' },
  { code: 'TO', pt: 'Tonga', en: 'Tonga', capital: "Nuku'alofa" },
  { code: 'TT', pt: 'Trinidad e Tobago', en: 'Trinidad and Tobago', capital: 'Port of Spain' },
  { code: 'TN', pt: 'Tunísia', en: 'Tunisia', capital: 'Tunis' },
  { code: 'TM', pt: 'Turcomenistão', en: 'Turkmenistan', capital: 'Ashgabat' },
  { code: 'TR', pt: 'Turquia', en: 'Turkey', capital: 'Ankara' },
  { code: 'TV', pt: 'Tuvalu', en: 'Tuvalu', capital: 'Funafuti' },
  { code: 'UA', pt: 'Ucrânia', en: 'Ukraine', capital: 'Kyiv' },
  { code: 'UG', pt: 'Uganda', en: 'Uganda', capital: 'Kampala' },
  { code: 'UY', pt: 'Uruguai', en: 'Uruguay', capital: 'Montevideo' },
  { code: 'UZ', pt: 'Uzbequistão', en: 'Uzbekistan', capital: 'Tashkent' },
  { code: 'VU', pt: 'Vanuatu', en: 'Vanuatu', capital: 'Port Vila' },
  { code: 'VA', pt: 'Vaticano', en: 'Vatican City', capital: 'Vatican City' },
  { code: 'VE', pt: 'Venezuela', en: 'Venezuela', capital: 'Caracas' },
  { code: 'VN', pt: 'Vietnã', en: 'Vietnam', capital: 'Hanoi' },
  { code: 'ZM', pt: 'Zâmbia', en: 'Zambia', capital: 'Lusaka' },
  { code: 'ZW', pt: 'Zimbábue', en: 'Zimbabwe', capital: 'Harare' },
]

export const COUNTRY_NAMES = {
  BR: 'Brazil',
  US: 'United States',
  GB: 'United Kingdom',
  CA: 'Canada',
  MX: 'Mexico',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colombia',
  PE: 'Peru',
  VE: 'Venezuela',
  UY: 'Uruguay',
  PY: 'Paraguay',
  BO: 'Bolivia',
  EC: 'Ecuador',
  FR: 'France',
  DE: 'Germany',
  IT: 'Italy',
  ES: 'Spain',
  PT: 'Portugal',
  NL: 'Netherlands',
  BE: 'Belgium',
  CH: 'Switzerland',
  AT: 'Austria',
  SE: 'Sweden',
  NO: 'Norway',
  DK: 'Denmark',
  FI: 'Finland',
  IE: 'Ireland',
  PL: 'Poland',
  CZ: 'Czech Republic',
  GR: 'Greece',
  TR: 'Turkey',
  RU: 'Russia',
  UA: 'Ukraine',
  JP: 'Japan',
  CN: 'China',
  KR: 'South Korea',
  IN: 'India',
  TH: 'Thailand',
  VN: 'Vietnam',
  PH: 'Philippines',
  ID: 'Indonesia',
  MY: 'Malaysia',
  SG: 'Singapore',
  AU: 'Australia',
  NZ: 'New Zealand',
  ZA: 'South Africa',
  EG: 'Egypt',
  MA: 'Morocco',
  NG: 'Nigeria',
  AE: 'United Arab Emirates',
  SA: 'Saudi Arabia',
  QA: 'Qatar',
  IL: 'Israel',
}

export const POSITIVE_WORDS = ['skyline', 'city', 'landmark', 'street', 'view', 'downtown', 'aerial', 'architecture', 'urban', 'sky', 'night', 'bridge', 'harbor', 'beach']
export const NEGATIVE_WORDS = ['portrait', 'person', 'face', 'fashion', 'model', 'food', 'animal', 'dog', 'cat', 'selfie', 'interior']
