export const COUNTRY_NAMES = {
  BR: 'Brazil',
  US: 'United States',
  GB: 'United Kingdom',
  CA: 'Canada',
  MX: 'Mexico',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colombia',
  PE: 'Peru',
  VE: 'Venezuela',
  UY: 'Uruguay',
  PY: 'Paraguay',
  BO: 'Bolivia',
  EC: 'Ecuador',
  FR: 'France',
  DE: 'Germany',
  IT: 'Italy',
  ES: 'Spain',
  PT: 'Portugal',
  NL: 'Netherlands',
  BE: 'Belgium',
  CH: 'Switzerland',
  AT: 'Austria',
  SE: 'Sweden',
  NO: 'Norway',
  DK: 'Denmark',
  FI: 'Finland',
  IE: 'Ireland',
  PL: 'Poland',
  CZ: 'Czech Republic',
  GR: 'Greece',
  TR: 'Turkey',
  RU: 'Russia',
  UA: 'Ukraine',
  JP: 'Japan',
  CN: 'China',
  KR: 'South Korea',
  IN: 'India',
  TH: 'Thailand',
  VN: 'Vietnam',
  PH: 'Philippines',
  ID: 'Indonesia',
  MY: 'Malaysia',
  SG: 'Singapore',
  AU: 'Australia',
  NZ: 'New Zealand',
  ZA: 'South Africa',
  EG: 'Egypt',
  MA: 'Morocco',
  NG: 'Nigeria',
  AE: 'United Arab Emirates',
  SA: 'Saudi Arabia',
  QA: 'Qatar',
  IL: 'Israel',
}

export const POSITIVE_WORDS = ['skyline', 'city', 'landmark', 'street', 'view', 'downtown', 'aerial', 'architecture', 'urban', 'sky', 'night', 'bridge', 'harbor', 'beach']

export const NEGATIVE_WORDS = ['portrait', 'person', 'face', 'fashion', 'model', 'food', 'animal', 'dog', 'cat', 'selfie', 'interior']
